upstream webserv_upstream {
    server webserv:8080;
}

upstream php {
    server php:9000;
}

server {
	listen 443 ssl;
	server_name localhost mchetoui.42.fr;
	ssl_protocols TLSv1.2 TLSv1.3;
	ssl_certificate /etc/nginx/ssl/inception.crt;
	ssl_certificate_key /etc/nginx/ssl/inception.key;

    # wordpress configuration
    root /var/www/wordpress;

    index index.php;

    location = /favicon.ico {
        log_not_found off;
        access_log off;
    }

    location = /robots.txt {
        allow all;
        log_not_found off;
        access_log off;
    }

    location / {
        try_files $uri $uri/ /index.php?$args;
    }

    location ~ \.php$ {
        include fastcgi.conf;
        fastcgi_intercept_errors on;
        fastcgi_pass php;
    }

    access_log /var/log/nginx/wordpress_access.log;
    error_log /var/log/nginx/wordpress_error.log;

    # webserv configuration
    location = /webserv {
        return 301 /webserv/;
    }

    location /webserv/ {
        proxy_pass http://webserv_upstream/;
        proxy_set_header Host webserv:8080;
        proxy_redirect ~^(/.*)$ /webserv$1;
    }

    location ~ ^/(desc|login|tests|uploads|cgi-bin)(/.*)?$ {
        proxy_pass http://webserv_upstream;
        proxy_set_header Host webserv:8080;
    }
}
