services:
  redis:
    container_name: redis
    networks: [inception]
    build:
      context: bonus/redis
    restart: unless-stopped
  lftp-tty:
    container_name: lftp-tty
    ports: ['7681:7681']
    build:
      context: bonus/lftp-tty
    restart: unless-stopped
  ftp:
    container_name: ftp
    volumes: ['wordpress:/srv/files/ftp']
    build:
      context: bonus/ftp
    restart: unless-stopped
  webserv:
    container_name: webserv
    networks: [inception]
    volumes: ['webserv:/webserv']
    build:
      context: bonus/webserv
    restart: unless-stopped
  mariadb:
    container_name: mariadb
    networks: [inception]
    env_file: .env
    volumes: ['mariadb:/var/lib/mysql']
    build:
      context: requirements/mariadb
      args:
        SQL_DATABASE: ${SQL_DATABASE}
        SQL_USER: ${SQL_USER}
        SQL_PASSWORD: ${SQL_PASSWORD}
        SQL_ROOT_PASSWORD: ${SQL_ROOT_PASSWORD}
    restart: unless-stopped
  nginx:
    container_name: nginx
    networks: 
      - inception
    depends_on: ['wordpress']
    ports: ["443:443"]
    build:
      context: requirements/nginx
    volumes: ['wordpress:/var/www/wordpress']
    restart: on-failure
  wordpress:
    container_name: wordpress
    networks: [inception]
    env_file: .env
    depends_on: ['mariadb']
    build:
      context: requirements/wordpress
      args:
        SQL_DATABASE: ${SQL_DATABASE}
        SQL_USER: ${SQL_USER}
        SQL_PASSWORD: ${SQL_PASSWORD}
    volumes: ['wordpress:/var/www/wordpress']
    restart: on-failure

volumes:
  wordpress:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: '/home/gnxrly/data/wordpress'
  webserv:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: '/home/gnxrly/data/webserv'
  mariadb:  
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: '/home/gnxrly/data/mariadb'

networks:
  inception:
    driver: bridge
