server {
    listen 0.0.0.0:8080;
    server_name webserv:8080;
    error_page 403 /webserv/sandbox/errors/403.html;
    error_page 404 /webserv/sandbox/errors/404.html;
    error_page 500 /webserv/sandbox/errors/500.html;
    client_max_body_size 10k;
    root /webserv/sandbox;
    location / {
        return 301 /desc;
        autoindex on;
        allow_methods GET;
    }
    location /desc {
        root /webserv/sandbox/desc;
        index index.html; 
        allow_methods GET;
    }
    location /login {
        root /webserv/sandbox/login;
        index index.html; 
        allow_methods GET;
    }
    location /tests {
        root /webserv/sandbox/tests;
        index index.html;
        allow_methods GET;
    }
    location /uploads {
        root /webserv/sandbox/uploads;
        upload_enable on;
        autoindex on;
        allow_methods POST PUT GET DELETE;
    }
    location /cgi-bin {
        root /webserv/sandbox/cgi-bin;
        cgi .py /usr/bin/python3;
        cgi .js /usr/bin/node;
        cgi .sh /usr/bin/bash;
        allow_methods GET;
    }
}